# Construction of beds 


In [6]:
function conelmtab(nx::Int, ny::Int)
    @assert nx ≥ 2 && ny ≥ 2 
    nx += 1
    ny += 1
    num_tris = 2 * (nx - 1) * (ny - 1)
    etoV = Matrix{Int}(undef, num_tris, 3)

    e = 1
    tl = 1 

    for col ∈ 1:(nx - 1)            
        tl = 1 + (col - 1) * ny   
        for row ∈ 1:(ny - 1)          
            tr = tl + ny
            bl = tl + 1
            br = tl + ny + 1
            
            #tri1
            etoV[e, 1] = tr
            etoV[e, 2] = tl
            etoV[e, 3] = br
            e += 1

            #tri2
            etoV[e, 1] = bl
            etoV[e, 2] = br
            etoV[e, 3] = tl
            e += 1

            tl += 1  #move one node down within the column
        end
    end

    return etoV
end

function calculate_bnodes(noelms1, noelms2)
    """
    Should work, please confirm 
    """
    bnodes = []
    for i ∈ 0:noelms1, j ∈ 0:noelms2
        if (i == 0 || i == noelms1 || j == 0 || j == noelms2)
            # push!(bnodes, (i, j, j+1 + i * (noelms1 + 1)))
            push!(bnodes, j+1 + i * (noelms2 + 1))
        end 
    end 
    return bnodes
end

EToV = conelmtab(4, 3)
bnodes = calculate_bnodes(4, 3)
println("EToV = ")
display(EToV)
println("bnodes = ")
display(bnodes)

EToV = 
bnodes = 


24×3 Matrix{Int64}:
  5   1   6
  2   6   1
  6   2   7
  3   7   2
  7   3   8
  4   8   3
  9   5  10
  6  10   5
 10   6  11
  7  11   6
  ⋮      
 11  15  10
 15  11  16
 12  16  11
 17  13  18
 14  18  13
 18  14  19
 15  19  14
 19  15  20
 16  20  15

14-element Vector{Any}:
  1
  2
  3
  4
  5
  8
  9
 12
 13
 16
 17
 18
 19
 20

In [ ]:
noelms1 = 4
noelms2 = 3 

EToV = conelmtab(noelms1, noelms2)
bnodes = calculate_bnodes(noelms1, noelms2)

M = size(EToV)[1]

beds = zeros(Int64, M, 2)

count = 1 
for idx in 1:M
    i, j, k = EToV[idx, :]
    TF_vector = Int.([i, j, k] .∈ [bnodes])

    if TF_vector == [0, 1, 1]
        println("weird idx = $idx")
    end 

    if sum(TF_vector) == 2 && TF_vector != [0, 1, 1] # element with 1 edge 
        inner_idx = findall(x -> x == 0, TF_vector)
        
        # improve! 
        first_idx = 99 
        if inner_idx == [1] 
            first_idx = 2 
        elseif inner_idx == [2]
            first_idx = 3 
        elseif inner_idx == [3]
            first_idx = 1
        else 
            println("fuck")
        end 

        beds[count, :] = [idx, first_idx]
        count += 1


    elseif sum(TF_vector) == 3 # element with 2 edges, see e6 or e9 in Fig 2.5
        # VERY unsure
        beds[count, :] = [idx, k]
        count += 1
        beds[count, :] = [idx, i]
        count += 1
    end 
    
end 

display(beds[1:count-1, :])

display(EToV)
display(bnodes)

weird idx = 5
weird idx = 20


14×2 Matrix{Int64}:
  1   1
  2   3
  4   3
  6   3
  6   4
  7   1
 12   1
 13   1
 18   1
 19  18
 19  17
 21   3
 23   3
 24   1

24×3 Matrix{Int64}:
  5   1   6
  2   6   1
  6   2   7
  3   7   2
  7   3   8
  4   8   3
  9   5  10
  6  10   5
 10   6  11
  7  11   6
  ⋮      
 11  15  10
 15  11  16
 12  16  11
 17  13  18
 14  18  13
 18  14  19
 15  19  14
 19  15  20
 16  20  15

14-element Vector{Any}:
  1
  2
  3
  4
  5
  8
  9
 12
 13
 16
 17
 18
 19
 20

In [8]:
TF_vector = Int.([5, 1, 6] .∈ [bnodes])
findall(x -> x == 0, TF_vector)

1-element Vector{Int64}:
 3

In [9]:
function ConstructBeds(EToV, bnodes)
    
end

ConstructBeds (generic function with 1 method)